# -*- coding: utf-8 -*-
"""csci1020_lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uNbM2jqxB3PbCBTxPFUaroE_Fcb6WcUx

1. Assume that we have our first DNA sequence that has a string as 'TTCATTTAT', which is comprised of four nucleotides (e.g. A, T, C, G). We would like to define a variable called 'DNA1', and assign the sequence to this variable. Then we need to print the variable by print("DNA1: ", DNA1)
"""

DNA1="TTCATTTAT"
print("DNA1:", DNA1)

"""2. Again, we have our second DNA sequence that has a string as 'AAAAATAAA'. We would like to assign this sequence to another variable called 'DNA2', and print the variable by print("DNA2: ", DNA2)."""

DNA2= "AAAAATAAA"
print("DNA2:", DNA2)

"""3.  Now we have got two sequences, which were assigned two variables, DNA1, and DNA2. We would like to calculate the length of the two sequences and assign the length values to new variables, named DNA1_length and DNA2_length. Similarly, please print the values of the new variables."""

DNA1="TTCATTTAT"
DNA2= "AAAAATAAA"

len(DNA1)
DNA1_length = len(DNA1)

len(DNA2)
DNA2_length = len(DNA2)

print(DNA1_length)
print(DNA2_length)

"""4. Based on the three steps above, we got two variables that store DNA sequences (DNA1, and DNA2), and also two variables that store the length of DNA sequences (DNA1_length and DNA2_length), We are curious about the equality of the length of two DNA sequences.
Please write your python codes for the following questions:

- Is the length of DNA1 equal to the length of DNA2?
- Is the length of DNA1  not equal to the length of DNA2?
- Is the length of DNA1 larger than the length of DNA2?
- Is the length of DNA1 smaller than the length of DNA2?
"""

DNA1="TTCATTTAT"
DNA2= "AAAAATAAA"

len(DNA1) == len(DNA2)

len(DNA1) != len(DNA2)

len(DNA1) > len(DNA2)

len(DNA1) < len(DNA2)

"""5.Now let's do some sequence manipulations in python. For sequences, DNA1, and DNA2
Please write your python codes for the following activities:

What is the first letter of the first sequence, DNA1?
What is the first letter of the second sequence, DNA2?
What is the last letter of the first sequence, DNA1?
What is the last letter of the second sequence, DNA2?
Are the first letters of two sequences the same?
Are the last letters of two sequences the same?
What is the 5th letter of the first sequence, DNA1?
What is the 5th letter of the second sequence, DNA2?
What are the first 5 letters of the first sequence, DNA1?
What are the first 5 letters of the second sequence, DNA2?
What are the last 5 letters of the first sequence, DNA1?
What are the last 5 letters of the second sequence, DNA2?
How to concatenate the last 5 letters of the first sequence and the last 5 letters of the second sequence together?
"""

DNA1=["T","T","C","A","T","T","T","A","T"]

print(DNA1[1:2])
print(DNA1[8:9])
print(DNA1[4:5])
print(DNA1[0:5])
print(DNA1[4:9])

DNA2= ["A", "A", "A", "A", "A", "T", "A", "A", "A"]
print(DNA2[1:2])
print(DNA2[8:9])
print(DNA2[4:5])
print(DNA2[0:5])
print(DNA2[4:9])

DNA1=["T","T","C","A","T","T","T","A","T"]
DNA2= ["A", "A", "A", "A", "A", "T", "A", "A", "A"]

print(DNA1[1:2]) != print(DNA2[1:2])
print(DNA1[8:9]) != print(DNA2[8:9])
DNA3 = (DNA1[4:9]) + (DNA2[4:9])
print(DNA3)

"""6. Let's continue with the sequence manipulations in python, but this time, we need to call some python's built-in functions. For sequences, DNA1, and DNA2
Please write your python codes for the following activities:

How many times does the character A appear in the first sequence DNA1? (hint: use the in-built function for string, count(); refer to https://www.geeksforgeeks.org/python-string-count/ (Links to an external site.)  )
How many times does the character A appear in the first sequence DNA2? (hint: use the in-built function for string, count(); refer to https://www.geeksforgeeks.org/python-string-count/ (Links to an external site.))
What is the index at which the first occurrence of the pattern AT begins in the first sequence DNA1? (hint: use str.index() or str.find(); refer to https://www.geeksforgeeks.org/python-string-find/ (Links to an external site.))
What is the index at which the first occurrence of the pattern AT begins in the second sequence DNA2? (hint: use str.index() or str.find(); refer to https://www.geeksforgeeks.org/python-string-find/ (Links to an external site.))

"""

DNA1="TTCATTTAT"
DNA2= "AAAAATAAA"
print(DNA1.count("A"))
print(DNA2.count("A"))
print(DNA1.index("AT"))
print(DNA2.index("AT"))

"""7. Calculate Genomics %G~C Content for DNA sequence 'TTAAGCGAAAGCTGCGTGCGTCT'

What is GC Content?
GC content is usually calculated as a percentage value and is sometimes called the G+C ratio or GC-ratio. Given a DNA sequence, the GC-content percentage is calculated as  
You need to think of a step-by-step implementation for this problem. The programming progress should be made through a few steps.
Write your python codes to calculate the GC content.
Validate your answers in this online tool: https://www.sciencebuddies.org/science-fair-projects/references/genomics-g-c-content-calculator (Links to an external site.) (we will learn how to design and implement this bioinformatics tool in later topics)
"""

DNA = "TTAAGCGAAAGCTGCGTGCGTCT"
print("G count:",round((DNA.count("G")/23)*100),"%")
print("C count:",round((DNA.count("C")/23)*100),"%")