# -*- coding: utf-8 -*-
"""final_exam_part2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q05Mt7TkBM09tn84vK02qUWgJf87Fzn5
"""

#Q1
DNA1 = 'CCAGGGGAGGTTCCTGAACAACACGGAGCTGCAGGCGGCGAACGGGAGGTTCCAGAGGGCGACGGC'
DNA2 ='GCGGCGGGGAGGTTCCCGAGCGGGAGCGACCTGGAGAGCGTGCAGGGGAACATACAGAGGAGCGC'
print("DNA1 is: ",DNA1)
print("DNA2 is: ",DNA2)

#Q2
DNA1 = 'CCAGGGGAGGTTCCTGAACAACACGGAGCTGCAGGCGGCGAACGGGAGGTTCCAGAGGGCGACGGC'
DNA2 = 'GCGGCGGGGAGGTTCCCGAGCGGGAGCGACCTGGAGAGCGTGCAGGGGAACATACAGAGGAGCGC'
DNA1_length = len(DNA1)
DNA2_length = len(DNA2)
print("Lenght of DNA1_length: ", DNA1_length)
print("Length of DNA2_length: ", DNA2_length)

from typing import Sequence
#Q3
DNA1 = 'CCAGGGGAGGTTCCTGAACAACACGGAGCTGCAGGCGGCGAACGGGAGGTTCCAGAGGGCGACGGC'
DNA2 ='GCGGCGGGGAGGTTCCCGAGCGGGAGCGACCTGGAGAGCGTGCAGGGGAACATACAGAGGAGCGC'
print(DNA1[0:10])
print(DNA2[0:10])
print(DNA1[56:66])
print(DNA2[55:65])
print(DNA1[63:66] == DNA2[55:65])
print(DNA1[61:66] == DNA2[60:65])
print(DNA1.count('A'))
print(DNA2.count('A'))

#Q4
DNA_motifs = ['TTCAT','AATCATGA','CCCG','GGCATT','CACGT']
print("DNA_motifs: ", DNA_motifs)
print(DNA_motifs[2])
print(DNA_motifs[0:2])
print(DNA_motifs[3:5])
DNA_motifs[0] and DNA_motifs[5]

#Q5
DNA_motifs_length = {'TTCAT':5,'AATCATGA':8,'CCCG':4,'GGCATT':6,'CACGT':5, 'CAAT':4 }
print("DNA_motifs_length : ", DNA_motifs_length)
values = DNA_motifs_length
DNA_motifs_length.count('CCT')

#Q6
DNA_motifs=['TTCAT','AATCATGA','CCCG','GGCATT','CACGT']
print("DNA_motifs:",DNA_motifs)

#Q7
####### Calculating the sequence identity for proteins
seq_alnA = 'GEIMAASRI'
seq_alnB = '-EKAA-SVI'
def Calculate_identity(seq_aln1, seq_aln2):

    ### check if two sequences have same length
    if len(seq_aln1) != len(seq_aln2):
        return

    ### Write your codes to calculate fraction of identical amino acids between two aligned sequences.
    ????????

    return identity

Calculate_identity(seq_alnA,seq_alnB )