# -*- coding: utf-8 -*-
"""Lab4 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1323K5ZY6jdR7v7i8WbIoHaZbnSNzgVOd
"""

def alignment_score(sequence1, sequence2, match=1, mismatch=-1, gap=-1):
  if len(sequence1) != len(sequence2):
    print('The two sequences must have the same length to calculate the alignment score')
    return
  score = 0
  for i in range(len(sequence1)):
    char1 = sequence1[i]
    char2 = sequence2[i]
    if (char1 == "-"):
      score = score + gap
    elif (char1 == char2):
      score = score + match
    elif (char1 != char2):
      score = score + mismatch
  print('Sequence 1: ', sequence1)
  print('Sequence 2: ', sequence2)
  print('Alignment Score: ', score)

"""Get input as below and print out "The two sequences must have the same length to calculate the alignment score" if the lengths of the two sequences are different.
alignment_score("AATATGATA", "AAGTTCATA"
alignment_score("AATATGATA", "AAGTTCATA", 2, -2, -2)
"""

alignment_score("AATATGATA", "AAGTTCATA")

"""Calculate the alignment score between sequences 'AATATGATA' and 'AAGTTCATA'? Please run in your jupyter notebook.

for match = 1, mismatch = -1, gap = -1,  score = ?

for match = 2, mismatch = -2, gap = -2,  score = ?
"""

alignment_score("AATATGATA", "AAGTTCATA", 2, -2, -2)

"""Calculate the alignment score between sequences 'A-TAT-ATA' and 'AATTTC-TA'? Please run in your jupyter notebook.

1. for match = 1, mismatch = -1, gap = -1,  score = ?

2. for match = 2, mismatch = -2, gap = -2,  score = ?
"""

alignment_score("A-TAT-ATA", "AATTTC-TA")

"""Calculate the alignment score between sequences 'AGCTGAA' and 'AATTTCAGAGA'? Please run your codes in your jupyter notebook. (Hint: this should return "The two sequences must have the same length to calculate the alignment score" without scoring)


"""

alignment_score("A-TAT-ATA", "AATTTC-TA", 2, -2, -2)

alignment_score("AGCTGAA", "AATTTCAGAGA")