# -*- coding: utf-8 -*-
"""lab8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ynz3fRQCCjIpeOjCsukyUlxW_6kdMgFg
"""

import turtle

phylotree = turtle.Turtle()

phylotree.clear()
phylotree.up()
phylotree.goto(-0.5*turtle.window_width(),0)
phylotree.down()
phylotree.setheading(0)

phylotree.forward(50)
phylotree.write(' A', font=('Arial', 10,'bold'))

phylotree.left(90)
phylotree.forward(50)
phylotree.right(90)
phylotree.forward(50)
phylotree.write(' B', font=('Arial', 10,'bold'))

phylotree.backward(50)
phylotree.right(90)
phylotree.forward(100)
phylotree.left(90)
phylotree.forward(50)
phylotree.write(' C', font=('Arial', 10, 'bold'))