# -*- coding: utf-8 -*-
"""Midterm_part2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DQt2LjjKVn9IUu4yxx6opvqZ5L5bI5xp
"""

DNA1 = 'ATCCGAATATGGACGGGGTA'
DNA2 = 'ATCCGAATACGGTTGGGTA'
DNA3 = 'ATCCAATACGGTTCGGGTA'
DNA4 = 'ATCCGAATACGGAAAGGGAAAGA'
DNA5 = 'ATAAAGCCGAATACGGAAAGGG'
DNA6 = 'AACCDDEE'
if DNA1 == DNA1:
  print("TATGG")
else:
  print("No found!")

if DNA2 != DNA2:
  print("TACGG")
else:
  print("No found!")

if DNA3 != DNA3:
  print("CCC")
else:
  print("No found!")

if DNA4 == DNA4:
  print("No found!")

get_between(dna, start_motif, end_motif)

get_between('ATCCGAATATGGACGGGGTA','CGAA','ACGG')
get_between('ATCCGAATACGGTTGGGTA','CGAA','CCCC')
get_between('ATCCAATACGGTTCGGGTA','CCC','CAA')
get_between('ATCCGAATACGGAAAGGGAAAGA','CGAA','AAAG')
get_between('ATAAAGCCGAATACGGAAAGGG','CGAA','AAAG')
get_between('AACCDDEE', 'CC', 'AA')
get_between('weconductbioinformaticsresearch!','conduct','research')