# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BiuTvH-lAt2lXg2PUFIcGkhhtLNvOQuU
"""

def show(a, b, c):
    print(f'{a}-{b}-{c}')

show(c=3, b=6, a=5)

def show_time(year, month, day, hour, minutes):
    print(f'{month}/{day}/{year} {hour}:{minutes}')

show_time(2017, 1, 27, minutes=30, hour=11)

def show(a, b, c=17):
    print(f'{b}-{c}-{a}')

show(7, 3)
show(9, 5, c=8)

def show(a, b=2, c=6):
    print(f'{c}/{b}/{a}')

show(b=9, a=7)
show(c=5, a=3)