# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_MOP76KbJ1Nl1GYv5Yq0TLeGiBDBY1kJ
"""

person = 'Cloud'
print(person[1])

person = 'Aerith'
print(person[1])

person = 'Tifa'
print(person[-3])

person1 = "Yuffie"
person2 = "Cloud"
person3 = person1 + person2
print(person3)

color = 'orange'
my_slice = color[5:6]
print(my_slice)

color = 'violet'
print(my_slice)

person_name = input('Person name: ')
person_age = int(input('Person age: '))

print('In 5 years', person_name, 'will be', person_age + 5)

item_info = 'Headphones 11 16'

item_tokens = item_info.split()
item = item_tokens[0]
quantity = item_tokens[1]
price = item_tokens[2]

print(f'{item} stock: {quantity}')
print(f'Price: {price}')

address = 'www.google.com'

separator = '/'
address_tokens = address.split('.')
print(separator.join(address_tokens))

number_string = input()
number_float = float(number_string)
number_int = int(number_float)
print(number_string)
print(number_float)
print(number_int)

num_owls_zoo1 = 1

num_owls_zoo2 = 2

num_owls_zoo3 = 3

num_owls_zoo4 = 4

zoos = 4

avg_owls = 0.0

avg_owls=(num_owls_zoo1+num_owls_zoo2+num_owls_zoo3+num_owls_zoo4)/zoos

print('Average owls per zoo:', int(avg_owls))

user_word = input()
user_number = int(input())

print(user_word,',',user_number)

num_difference = int(input())  # Program will be tested with values: -14, -15, -16, -17.

if num_difference == -16:
    total_difference == -25
else:
    total_difference=num_difference

print(total_difference)

x = int(input())

if x < 15:
    print('o')
elif x == 15:
    print('p')
elif x <= 25:
    print('q')
else:
    print('t')

user_age = int(input())

if (user_age >= 18) and (user_age <= 25):
    print('Eligible')
else:
    print('Ineligible')

a = 'snake'
b = 'shark'
c = [a, b]
d = c
d[0] = 'mouse'

if (b is d[1]):
    print('f')
if (a is d[0])
    print('g')
if (c is d):
    print('h')

cities = {
    'Rome': 5259,
    'Paris': 584,
    'Austin': 3435,
}

best = ''
distance = 0
for city in cities:
    if cities[city] > distance:
        best = city
        distance = cities[city]
print(best, distance)

user_values = [3, 5, 7]
user_values[1] = user_values[2]
user_values[2] = user_values[0]

print(user_values)

# "New" means new compared to previous level
provincial_capitals = {
    'Alberta': 'Edmonton',
    'Ontario': 'Toronto',
    'BC': 'Victoria',
    'Nunavut': 'Iqaluit'
}

province_name = input()
while province_name != 'exit':
    if province_name in provincial_capitals:
        print(provincial_capitals[province_name])
        del provincial_capitals[province_name] # New line
    else:
        print('x')
    province_name = input()



print("Let's play the Mystery code game!")

import random

code = random.randrange(0,9)

guess = int(input("Here are the digits that are valid guesses: \n"))
if (guess == code):
    print("Congratulations, you won!")
else:
    ctr = 0
    while (guess != code):
        ctr += 1
        count = 0
        guess = str(guess)
        code = str(code)
        correct = ['X']*4
        for i in range(0, 4):
            if (guess[i] == code[i]):
                count += 1
                correct.append(guess[i])
            else:
                continue
        if (count < 4) and (count != 0):
            print("You guessed ",count," correctly")
            print('\n')
            n = int(input("Enter your guess: \n"))

        elif (count == 0):
            print("Sorry, you loose!")
            n = int(input("Enter your guess: \n"))

    if n == code:
        ctr+=1
        print("Congratulations, you won!")
        print("It took you only", ctr, "tries.")

from string import digits
import random
code = random.randrange (1000,10000)
print(code)
chances = 5
guess = int(input(f'Enter a 4 digit number and you have {chances} guesses: '))
if guess == code:
  print("Congratulations, you won!")
else:
  guesses = 0
  while guess != code and chances:
    guesses += 1
    chances -= 1
    digit = 0
    guess = str(guess)
    code = str(code)
    correct = ['X'] * 4
    for i in range (0,4):
      if guess[i] == code[i]:
        digit += 1
        correct[i] = code[i]
    if digit < 4 and digit > 0 and chances:
      print("You guessed", digit, "number correctly.")
      print('Here are the numbers you have right now: ')
      for num in correct:
        print(num, end="")
      print('\n')
      guess = int(input(f'Enter a 4 digit number and you have guess {chances} left: '))
    elif digit == 0 and chances:
      print("You guessed ",chances," correctly")
      guess = int(input(f'Enter a 4 digit number and you have guess {chances} left: '))
  if guess == code:
    print("Congratulations, you won!")
  if chances == 0:
     print("Sorry, you loose!")

def get_numbers():
    user_input = input()
    values = []
    for token in user_input.split():
        values.append(int(token))
    return values

def print_selected_numbers():
    numbers = get_numbers()
    for number in numbers:
        if (number % 5) == 0:
            print(number)

print_selected_numbers()