# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZV0RNhhjEdhY_H6ZveTf509b5P0SQonr
"""

import arithmetic

def calculate(number):
    return number + 5

print(calculate(1))
print(arithmetic.calculate(1))