# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vMVPrrVyr-gcXelmi50nlO-h151F6lqM
"""

def calculate(number):
    return number * 5

def calculate(number):
    return number - 5

print(calculate(3))
print(arithmetic.calculate(3))