# -*- coding: utf-8 -*-
"""week4_lec2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EcM_g6ZfN06CY87P2tox-qU-ZH3Triei
"""

pip install biopython

import Bio

from Bio.SeqUtils import GC
myDNA = 'ABCD'
GC(myDNA)

GC('ACTGN')

import Bio
Bio.SeqUtils.GC('ACTGN')

import numpy as np
import matplotlib.pyplot as plt

data = np.random.randint(low=0, high=50, size=100)
plt.plot(data)
plt.show()

!pip freeze