# -*- coding: utf-8 -*-
"""week3_lec1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vo0qxSnVMKsOX6Tv0En-EI7NCByD1D2Z
"""

3 == -4

3 == 3

3 == 3.0

type(3)

3 > -4

x = 3

x = 3
x > 3 and X < 100

x >= 3 and x < 100

if True:
  print("I am true")
else:
  print("I am false")

if 5 > 2:
  print("Yes 5 > 2")

num = 0
while num < 10:
  print(num, "SLU")
  num = num + 1

for person in ["person1", "person2", "person3", "person4"]:
  print(person, "get the order")

