# -*- coding: utf-8 -*-
"""week2 _lec1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lyFyaWUwxVU3rgJUZtl9PYK_uwpIBYFM
"""

print(3*2+5)